import { SessionProvider } from 'next-auth/react';
import { Inter } from 'next/font/google';
import AuthProvider from '@/components/AuthProvider';
import Header from '@/components/Header';
import '@/styles/globals.css';

export const revalidate = 0;

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  // Q: 下面的AuthProvider组件似乎是要传入session的
  // A: 不需要传session，因为AuthProvider组件内部会自动获取session
  return (
    <html lang='en'>
      <body className='bg-gray-100'>
        <AuthProvider>
          <header className='shadow-md'>
            <Header />
          </header>
          <main>{children}</main>
          {/* <footer>footer</footer> */}
        </AuthProvider>
      </body>
    </html>
  );
}
